# Generated by Django 4.2.6 on 2023-10-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
